const pageRoutes = {
  palette_platform: '/',
  client_view: '/client-view',
  account_hierarchy: '/account-hierarchy',
  custodian_view: '/custodian-view',
  manager_view: '/manager-view',
  relationship_tracking: '/relationship-tracking',
  top_activity: '/top-activity',
  alternative_investments: '/alternative-investments',
  investment_gain_loss: '/investment-gain-loss',
  market_value: '/market-value',
  portfolio_summary: '/portfolio-summary',
  realized_gain_loss: '/realized-gain-loss',
  security_screener: '/security-screener',
  style_performance: '/style-performance',
  transaction_audit: '/transaction-audit',
  transactions: '/transactions',
  unrealized_gain_loss: '/unrealized-gain-loss',
  report_management: '/report-management',
  published_reports: '/published-reports',
  rebalance_report: '/rebalance-report',
  report_run_scheduler: '/report-run-scheduler',
  schedule_report_manager: '/scheduler-report-manager',
  report_pack_manager: '/report-pack-manager',
  pivot_analyzer: '/pivot-analyzer',

  account_summery: '/account-summery',
  asset_allocation: '/asset-allocation',
  asset_allocation_target_ranges: '/asset-allocation-target-ranges',
  composite_flows: '/composite-flows',
  fixed_income: '/fixed-income',
  manager_performance: '/manager-performance',
  market_value_log: '/market-value-log',

  custodian_forms: '/custodian-forms',
  invoices: '/invoices',
  loas: '/loas',
  statements: '/statements',
  client_reports: '/client-reports',
  other_documents: '/other-documents',

  asset_hierarchy: '/asset-hierarchy',
  benchmark_maintenance: '/benchmark-maintenance',
  client_hierarchy: '/client-hierarchy',
  performance_backfill: '/performance-backfill',
  security_overrides: '/security-overrides',
  login_report: '/login-report',
  growth_summary: '/growth-summary',
  client_fact_sheet: '/client-fact-sheet',
  transaction_count: '/transaction-count',
  search_accounts: '/search-accounts',
  contacts: '/contacts',
  partnerships: '/partnerships',
  site_search: '/site-search',
  new_alert: '/new-alert',
  my_alert: '/my-alert',
  add_new_alert: '/add-new-alert',

  collaboration_center: '/collaboration-center',
  collaboration_asset_hierarchy: '/asset_hierarchy',
  benchmark: '/benchmark',
  fx_conversion_rates: '/fx-conversion-rates',
  missing_cost: '/missing-cost',
  last_statement_date: '/last-statement-date',
  platform_login_report: '/platform-login-report',
  library: '/library',
  collabration_custodian_forms: '/collabration-custodian-forms',
  collabration_customized_reports: '/collabration-customized-reports',
  collabration_documents: '/collabration-documents',
  collabration_invoices: '/collabration-invoices',
  collabration_loas: '/collabration-loas',
  collabration_statements: '/collabration-statements',
  collabration_batch_reports: '/collabration-batch-reports',
  collabration_site_pages: '/collabration-site',
  collabration_pages: '/collabration-pages',
  collabration_create: '/create',
  collabration_workflows: '/workflows',
  collabration_lists: '/lists',
  collabration_calendar: '/calendar',
  collabration_contacts: '/collabration-contacts',
  collabration_issues: '/collabration-issues',
  collabration_tasks: '/collabration-tasks',
  workflow_tasks: '/workflow-tasks',
  collabration_form_templates: '/form-templates',
  collabration_batch_files: '/collabration-batch-files',
  manage_permissions: '/permissions',

  tax_lot_log: '/tax-lot-log',
  wealth_overview: '/wealth-overview',
  extended_report_data: '/extended-report-data',
};

export default pageRoutes;
